### ISSUE TITLE
Spike - Research KMS/AWS ENCRYPTION

### ISSUE THREAD

**Issue by Beardnoceris** [Spooky-Action-Developers/Project-Ironclad#59]
As a Mozilla Employee, I want to be able to encrypt my secrets, so that I can store them more securely in dynamoDb.

**Comment by econmang** [comment]
Thanks for figuring out what spikes are called! Also, wanted to give brief update on my research thus far:

- We need to add a master key to our AWS account (This will cost about $1/month to use)

- We need to add edit to put_item in next Sprint

- This edit needs to extend the range of our put (need to add secret field)

- Need to add encryption method to lib.rs for the secret field.

- Make version a flag instead of required command

Adding the master key to our KMS allows us to utilize encryption. This will allow us to extend the fields of in our main function. Then, we can keep our name structure the same and not modify the list function. This also clears up some of our confusion about our method of storage.
